import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../../styles/Home.module.css'

export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filme detalhe:{info.title}
        </h1>

        <Link href="/busca">Ir para busca</Link>

        <p>{info.overview}</p>

        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="400" alt={info.title} />



      </main>

    </div>
  )
}


export async function getServerSideProps(context){
    const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
    const json = await res.json();
  
    return {
      props: {
        info: json.info
      }
    }
  }
  